In [1]:
import os
import pandas as pd
import numpy as np
import re
import string
import pickle

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.decomposition import TruncatedSVD, LatentDirichletAllocation
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import MinMaxScaler
from scipy.sparse import hstack

import lightgbm as lgb
import optuna

In [2]:
df = pd.read_csv("../data/raw/recipes.csv")

df["text"] = (
    df["Name"].fillna('') + " " +
    df["RecipeIngredientParts"].fillna('') + " " +
    df["RecipeInstructions"].fillna('')
)

df = df.dropna(subset=["AggregatedRating"]).reset_index(drop=True)

In [3]:
def preprocess(text):
    text = text.lower()
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = re.sub(r'\d+', '', text)
    return text

df["clean_text"] = df["text"].apply(preprocess)

In [4]:
tfidf = TfidfVectorizer(ngram_range=(1,1), max_features=5000)
X_tfidf = tfidf.fit_transform(df["clean_text"])

lsa = TruncatedSVD(n_components=100, random_state=0)
X_lsa = lsa.fit_transform(X_tfidf)

count_vec = CountVectorizer(max_features=5000)
X_count = count_vec.fit_transform(df["clean_text"])
lda = LatentDirichletAllocation(n_components=20, random_state=0)
X_lda = lda.fit_transform(X_count)

X_final = hstack([X_tfidf, X_lsa, X_lda]).tocsr()

In [5]:
y = df["AggregatedRating"].values

X_train, X_test, y_train, y_test = train_test_split(
    X_final, y, test_size=0.2, random_state=42
)

In [12]:
def objective(trial):
    param = {
        "objective": "regression",
        "metric": "rmse",
        "verbosity": -1,
        "boosting_type": "gbdt",
        "n_estimators": trial.suggest_int("n_estimators", 100, 500),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.1, log=True),
        "num_leaves": trial.suggest_int("num_leaves", 2, 256),
        "subsample": trial.suggest_float("subsample", 0.4, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.4, 1.0),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
    }
    
    gbm = lgb.LGBMRegressor(**param)
    gbm.fit(X_train, y_train, eval_set=[(X_test, y_test)])
    
    preds = gbm.predict(X_test)
    return np.sqrt(mean_squared_error(y_test, preds))

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=30, n_jobs=-1)

print(f"Best RMSE: {study.best_trial.value}")

[I 2026-03-27 22:44:55,423] A new study created in memory with name: no-name-3bb8eb54-aae3-410b-ad83-7abcb8ffc984
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 22:46:40,066] Trial 1 finished with value: 0.6386837674761829 and parameters: {'n_estimators': 118, 'learning_rate': 0.0026812918470580666, 'num_leaves': 13, 'subsample': 0.46754956710348733, 'colsample_bytree': 0.792885331721446, 'min_child_samples': 19}. Best is trial 1 with value: 0.6386837674761829.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 22:56:22,998] Trial 4 finished with value: 0.6324003387378706 and parameters: {'n_estimators': 184, 'learning_rate': 0.050645312508922756, 'num_leaves': 123, 'subsample': 0.40053507637782737, 'colsample_bytree': 0.48750880477413827, 'min_child_samples': 18}. Best is trial 4 with value: 0.6324003387378706.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 22:56:47,993] Trial 8 finished with value: 0.6315823948269135 and parameters: {'n_estimators': 287, 'learning_rate': 0.054252277101255325, 'num_leaves': 41, 'subsample': 0.4293777123500978, 'colsample_bytree': 0.7628432372090888, 'min_child_samples': 72}. Best is trial 8 with value: 0.6315823948269135.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 22:59:18,885] Trial 2 finished with value: 0.6325951892329595 and parameters: {'n_estimators': 483, 'learning_rate': 0.009360277995711578, 'num_leaves': 41, 'subsample': 0.8165252351446316, 'colsample_bytree': 0.5877787922598705, 'min_child_samples': 54}. Best is trial 8 with value: 0.6315823948269135.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:05:02,263] Trial 6 finished with value: 0.6314678026497071 and parameters: {'n_estimators': 361, 'learning_rate': 0.014324520282306344, 'num_leaves': 104, 'subsample': 0.8795998801528702, 'colsample_bytree': 0.561399678190891, 'min_child_samples': 99}. Best is trial 6 with value: 0.6314678026497071.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:07:05,624] Trial 3 finished with value: 0.6338862307087324 and parameters: {'n_estimators': 351, 'learning_rate': 0.006462724695012699, 'num_leaves': 83, 'subsample': 0.7357389129438768, 'colsample_bytree': 0.6044213398427211, 'min_child_samples': 14}. Best is trial 6 with value: 0.6314678026497071.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:07:29,187] Trial 5 finished with value: 0.6334964388935065 and parameters: {'n_estimators': 218, 'learning_rate': 0.007232637003711369, 'num_leaves': 206, 'subsample': 0.7383572685431896, 'colsample_bytree': 0.5201174787672886, 'min_child_samples': 72}. Best is trial 6 with value: 0.6314678026497071.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:08:10,887] Trial 0 finished with value: 0.6321950595997269 and parameters: {'n_estimators': 485, 'learning_rate': 0.010959615914444552, 'num_leaves': 90, 'subsample': 0.8991130334697537, 'colsample_bytree': 0.4445776602146869, 'min_child_samples': 13}. Best is trial 6 with value: 0.6314678026497071.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:11:42,761] Trial 7 finished with value: 0.6338698782410497 and parameters: {'n_estimators': 382, 'learning_rate': 0.005021413089986944, 'num_leaves': 78, 'subsample': 0.8279568828278558, 'colsample_bytree': 0.9879737925931634, 'min_child_samples': 45}. Best is trial 6 with value: 0.6314678026497071.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:13:46,510] Trial 9 finished with value: 0.6326812023783518 and parameters: {'n_estimators': 122, 'learning_rate': 0.06846979122417217, 'num_leaves': 211, 'subsample': 0.7990044545823203, 'colsample_bytree': 0.7643190266613554, 'min_child_samples': 99}. Best is trial 6 with value: 0.6314678026497071.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:14:24,687] Trial 11 finished with value: 0.6335116739740262 and parameters: {'n_estimators': 115, 'learning_rate': 0.013523379721462584, 'num_leaves': 177, 'subsample': 0.5600530690148713, 'colsample_bytree': 0.913339557225018, 'min_child_samples': 83}. Best is trial 6 with value: 0.6314678026497071.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:19:38,674] Trial 13 finished with value: 0.6352452402507606 and parameters: {'n_estimators': 261, 'learning_rate': 0.005109303871027619, 'num_leaves': 70, 'subsample': 0.9544008702162078, 'colsample_bytree': 0.7785153757689692, 'min_child_samples': 13}. Best is trial 6 with value: 0.6314678026497071.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:19:53,447] Trial 15 finished with value: 0.6380683911638004 and parameters: {'n_estimators': 228, 'learning_rate': 0.0013855123852090146, 'num_leaves': 75, 'subsample': 0.47307586557233416, 'colsample_bytree': 0.6204798203950159, 'min_child_samples': 33}. Best is trial 6 with value: 0.6314678026497071.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:24:18,831] Trial 14 finished with value: 0.6317911785220804 and parameters: {'n_estimators': 491, 'learning_rate': 0.03776301337255987, 'num_leaves': 58, 'subsample': 0.5402886516824564, 'colsample_bytree': 0.9813608860099168, 'min_child_samples': 37}. Best is trial 6 with value: 0.6314678026497071.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:29:21,572] Trial 10 finished with value: 0.6370556640476849 and parameters: {'n_estimators': 349, 'learning_rate': 0.0012737338752177273, 'num_leaves': 214, 'subsample': 0.6351640577303488, 'colsample_bytree': 0.5401956411322719, 'min_child_samples': 45}. Best is trial 6 with value: 0.6314678026497071.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:30:58,839] Trial 16 finished with value: 0.6381553274709383 and parameters: {'n_estimators': 165, 'learning_rate': 0.001497507775366868, 'num_leaves': 182, 'subsample': 0.7484611822859879, 'colsample_bytree': 0.8024953787713262, 'min_child_samples': 37}. Best is trial 6 with value: 0.6314678026497071.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:36:52,594] Trial 12 finished with value: 0.6333427790464663 and parameters: {'n_estimators': 408, 'learning_rate': 0.05223079583224115, 'num_leaves': 145, 'subsample': 0.617317773410019, 'colsample_bytree': 0.8307232592106337, 'min_child_samples': 37}. Best is trial 6 with value: 0.6314678026497071.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:40:58,024] Trial 18 finished with value: 0.6311883923138901 and parameters: {'n_estimators': 287, 'learning_rate': 0.028475805934315687, 'num_leaves': 144, 'subsample': 0.99028878653649, 'colsample_bytree': 0.6965658625012939, 'min_child_samples': 94}. Best is trial 18 with value: 0.6311883923138901.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:45:44,094] Trial 20 finished with value: 0.6314233496935587 and parameters: {'n_estimators': 332, 'learning_rate': 0.03177337955259903, 'num_leaves': 143, 'subsample': 0.5931467194459886, 'colsample_bytree': 0.6863715860823031, 'min_child_samples': 95}. Best is trial 18 with value: 0.6311883923138901.
[I 2026-03-27 23:45:44,618] Trial 19 finished with value: 0.6310870558770564 and parameters: {'n_estimators': 332, 'learning_rate': 0.025282213144442497, 'num_leaves': 142, 'subsample': 0.6250205587973491, 'colsample_bytree': 0.6600998660223271, 'min_child_samples': 98}. Best is trial 19 with value: 0.6310870558770564.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:49:44,156] Trial 21 finished with value: 0.6307625584919334 and parameters: {'n_estimators': 331, 'learning_rate': 0.02521612428766526, 'num_leaves': 137, 'subsample': 0.6279921765638963, 'colsample_bytree': 0.6782789638035118, 'min_child_samples': 99}. Best is trial 21 with value: 0.6307625584919334.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:50:03,194] Trial 17 finished with value: 0.6310616159801038 and parameters: {'n_estimators': 402, 'learning_rate': 0.021940088994257465, 'num_leaves': 159, 'subsample': 0.9748602631540543, 'colsample_bytree': 0.9347345989240268, 'min_child_samples': 100}. Best is trial 21 with value: 0.6307625584919334.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:53:30,838] Trial 23 finished with value: 0.6309716714302522 and parameters: {'n_estimators': 306, 'learning_rate': 0.023802764019352243, 'num_leaves': 128, 'subsample': 0.9983958612214721, 'colsample_bytree': 0.6797897676369605, 'min_child_samples': 100}. Best is trial 21 with value: 0.6307625584919334.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-27 23:54:43,122] Trial 22 finished with value: 0.6311259680237685 and parameters: {'n_estimators': 298, 'learning_rate': 0.02207312670501226, 'num_leaves': 153, 'subsample': 0.9973424169685411, 'colsample_bytree': 0.6879637466497461, 'min_child_samples': 100}. Best is trial 21 with value: 0.6307625584919334.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-28 00:08:37,068] Trial 24 finished with value: 0.6310580949360106 and parameters: {'n_estimators': 301, 'learning_rate': 0.024316211222675806, 'num_leaves': 253, 'subsample': 0.9697349586064039, 'colsample_bytree': 0.6892618529266997, 'min_child_samples': 100}. Best is trial 21 with value: 0.6307625584919334.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-28 00:11:45,371] Trial 25 finished with value: 0.6308867637592541 and parameters: {'n_estimators': 331, 'learning_rate': 0.022078649462498996, 'num_leaves': 248, 'subsample': 0.9774706038824632, 'colsample_bytree': 0.6632867489472102, 'min_child_samples': 100}. Best is trial 21 with value: 0.6307625584919334.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-28 00:11:53,714] Trial 26 finished with value: 0.6312229617386719 and parameters: {'n_estimators': 302, 'learning_rate': 0.022743373392069832, 'num_leaves': 243, 'subsample': 0.9776510094258116, 'colsample_bytree': 0.6800713646434043, 'min_child_samples': 86}. Best is trial 21 with value: 0.6307625584919334.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-28 00:12:16,243] Trial 27 finished with value: 0.630895398250117 and parameters: {'n_estimators': 425, 'learning_rate': 0.021425307533123442, 'num_leaves': 166, 'subsample': 0.666641159923519, 'colsample_bytree': 0.6768621135386821, 'min_child_samples': 86}. Best is trial 21 with value: 0.6307625584919334.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-28 00:12:23,957] Trial 28 finished with value: 0.6311374780236141 and parameters: {'n_estimators': 292, 'learning_rate': 0.02220383636601929, 'num_leaves': 246, 'subsample': 0.671422125517557, 'colsample_bytree': 0.6743221560172427, 'min_child_samples': 86}. Best is trial 21 with value: 0.6307625584919334.
/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-03-28 00:13:01,381] Trial 29 finished with value: 0.6312366332330674 and parameters: {'n_estimators': 427, 'learning_rate': 0.02063187820956694, 'num_leaves': 251, 'subsample': 0.6662385928489309, 'colsample_bytree': 0.6446859259375017, 'min_child_samples': 84}. Best is trial 21 with value: 0.6307625584919334.

Best RMSE: 0.6307625584919334

In [7]:
best_model = lgb.LGBMRegressor(**study.best_trial.params)
best_model.fit(X_train, y_train)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 1.236231 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 710622
[LightGBM] [Info] Number of data points in the train set: 215435, number of used features: 5111
[LightGBM] [Info] Start training from score 4.631040

LGBMRegressor(colsample_bytree=0.7808569649996221,
              learning_rate=0.02944304042220195, min_child_samples=41,
              n_estimators=459, num_leaves=102, subsample=0.9788057000162969)

In [8]:
with open('../resources/recipe_recommendation_model.pkl', 'wb') as f:
    pickle.dump({
        'model': best_model,
        'tfidf': tfidf,
        'lsa': lsa,
        'count_vec': count_vec,
        'lda': lda,
        'X_final': X_final 
    }, f)

In [9]:
def recommend_for_user(user_recipe_ids, top_k=10):
    indices = df[df["RecipeId"].isin(user_recipe_ids)].index
    
    if len(indices) == 0:
        return "No valid user recipes"
        
    user_profile = X_final[indices].mean(axis=0)
    similarity_scores = np.asarray(X_final @ user_profile.T).flatten()
    
    predicted_ratings = best_model.predict(X_final)
    
    scaler = MinMaxScaler()
    normalized_similarity = scaler.fit_transform(similarity_scores.reshape(-1, 1)).flatten()
    normalized_ratings = scaler.fit_transform(predicted_ratings.reshape(-1, 1)).flatten()
    
    df["final_score"] = (normalized_similarity * 0.7) + (normalized_ratings * 0.3)
    
    recs = df.drop(indices).sort_values("final_score", ascending=False)
    return recs[["RecipeId", "Name", "AggregatedRating", "final_score"]].head(top_k)

In [13]:
sample_recipes = df.sample(5)
sample_ids = sample_recipes["RecipeId"].tolist()

display(sample_recipes[["RecipeId", "Name"]])
display(recommend_for_user(sample_ids))

        RecipeId                                               Name
8553       14435                                           Squirnip
80055     112118  Yellow Maize Flour and Fenugreek Leaves Indian...
266069    507136                              Brazilian-Style Beans
34908      49284                                        Swiss Pears
132606    197565                  Emily's Easy Peanut Butter Candy!

/opt/homebrew/anaconda3/envs/SE481/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

,RecipeId,Name,AggregatedRating,final_score
110636,160537,Slow-Cooked White Beans,5.0,0.837314
114236,166703,Mixed Bean Chili,5.0,0.831140
132846,198003,Sauteed Green Beans and Red Onion,5.0,0.822552
59970,83612,Jamaica Me Crazy Chili,5.0,0.821438
243486,427708,Quick Southwestern Black Beans,5.0,0.820149
131687,195907,Pumpkin Chili,4.0,0.809919
238724,415168,Crispy Bacon Green Beans,5.0,0.806458
2776,6555,Red Beans With Rice,5.0,0.806315
142793,215362,Spicy Vegetarian Chili,5.0,0.806124
209540,345162,Paul's Vegetarian Chili,5.0,0.805884